name: theology_bot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.0
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  json_serializable: ^6.0.1
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
