name: theology_bot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  #cloud_firestore: 4.17.4
  envied: ^0.5.4+1
  firebase_core: ^2.31.0
  firebase_storage: ^11.6.5
  #firebase_ui_firestore: ^1.6.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.0.0
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  langchain: ^0.7.5
  langchain_community: ^0.3.1
  langchain_openai: ^0.7.1
  objectbox: ^4.0.2
  objectbox_flutter_libs: any
  path: ^1.9.0
  path_provider: ^2.1.4
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  envied_generator: ^0.5.4+1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  json_serializable: ^6.0.1
  objectbox_generator: any
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
