// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFdCsCtr0YjZLc9o7H_54wWbC69f4NiwU',
    appId: '1:552532248856:web:6d2f33e373f2a82b61f66d',
    messagingSenderId: '552532248856',
    projectId: 'theology-bot',
    authDomain: 'theology-bot.firebaseapp.com',
    storageBucket: 'theology-bot.appspot.com',
    measurementId: 'G-4J0T2MNHFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsYzJTdhSmNtP4B0_mr96CIbhjSpng23s',
    appId: '1:552532248856:android:07077b26e378721f61f66d',
    messagingSenderId: '552532248856',
    projectId: 'theology-bot',
    storageBucket: 'theology-bot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLAhiNqy-RyVZ_s4DuVQABv-CeNWn1cmg',
    appId: '1:552532248856:ios:96540f25563202aa61f66d',
    messagingSenderId: '552532248856',
    projectId: 'theology-bot',
    storageBucket: 'theology-bot.appspot.com',
    iosBundleId: 'com.example.theologybot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLAhiNqy-RyVZ_s4DuVQABv-CeNWn1cmg',
    appId: '1:552532248856:ios:96540f25563202aa61f66d',
    messagingSenderId: '552532248856',
    projectId: 'theology-bot',
    storageBucket: 'theology-bot.appspot.com',
    iosBundleId: 'com.example.theologybot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFdCsCtr0YjZLc9o7H_54wWbC69f4NiwU',
    appId: '1:552532248856:web:08bf8594bc70ec3961f66d',
    messagingSenderId: '552532248856',
    projectId: 'theology-bot',
    authDomain: 'theology-bot.firebaseapp.com',
    storageBucket: 'theology-bot.appspot.com',
    measurementId: 'G-PDPNW3CCPF',
  );

}