// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'app/features/ai/domain/tb_document.dart';
import 'app/features/profile/domain/profile.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2246371080391273654),
      name: 'TbDocument',
      lastPropertyId: const obx_int.IdUid(5, 9023067105925775344),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5291192030193256071),
            name: 'internalId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3119469556551188322),
            name: 'id',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(1, 5604955065836415858)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4617200983847387491),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7405803101028002447),
            name: 'metadata',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 9023067105925775344),
            name: 'embedding',
            type: 28,
            flags: 8,
            indexId: const obx_int.IdUid(2, 3116194390691805316),
            hnswParams: obx_int.ModelHnswParams(
              dimensions: 512,
            ))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 224130010904490608),
      name: 'Profile',
      lastPropertyId: const obx_int.IdUid(6, 8965919774584081652),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4296026325912946668),
            name: 'boxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6982771925802327144),
            name: 'id',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(3, 1406737739599029238)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7107130893629035554),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5958229889687295430),
            name: 'profileImageUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8837760849748310328),
            name: 'profileThumbnail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8965919774584081652),
            name: 'status',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(6, 224130010904490608),
      lastIndexId: const obx_int.IdUid(3, 1406737739599029238),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [
        1370905150836732587,
        8623016825720647224,
        9116967582977515539,
        6174992555003198125
      ],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        6976096780125484931,
        7645535157839673527,
        1319827446310171537,
        8875982733939597389,
        6207064549294037064,
        6703105257602444850,
        9097676760113123382,
        3588477275237611149,
        3163446296991798482,
        5374135653240222370,
        3365964145155816458,
        7319286834269331115,
        3396348169554592382,
        1350532771719394295
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    TbDocument: obx_int.EntityDefinition<TbDocument>(
        model: _entities[0],
        toOneRelations: (TbDocument object) => [],
        toManyRelations: (TbDocument object) => {},
        getId: (TbDocument object) => object.internalId,
        setId: (TbDocument object, int id) {
          object.internalId = id;
        },
        objectToFB: (TbDocument object, fb.Builder fbb) {
          final idOffset = fbb.writeString(object.id);
          final contentOffset = fbb.writeString(object.content);
          final metadataOffset = fbb.writeString(object.metadata);
          final embeddingOffset = fbb.writeListFloat32(object.embedding);
          fbb.startTable(6);
          fbb.addInt64(0, object.internalId);
          fbb.addOffset(1, idOffset);
          fbb.addOffset(2, contentOffset);
          fbb.addOffset(3, metadataOffset);
          fbb.addOffset(4, embeddingOffset);
          fbb.finish(fbb.endTable());
          return object.internalId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final metadataParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final embeddingParam =
              const fb.ListReader<double>(fb.Float32Reader(), lazy: false)
                  .vTableGet(buffer, rootOffset, 12, []);
          final object = TbDocument(
              id: idParam,
              content: contentParam,
              metadata: metadataParam,
              embedding: embeddingParam)
            ..internalId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Profile: obx_int.EntityDefinition<Profile>(
        model: _entities[1],
        toOneRelations: (Profile object) => [],
        toManyRelations: (Profile object) => {},
        getId: (Profile object) => object.boxId,
        setId: (Profile object, int id) {
          object.boxId = id;
        },
        objectToFB: (Profile object, fb.Builder fbb) {
          final idOffset = fbb.writeString(object.id);
          final nameOffset = fbb.writeString(object.name);
          final profileImageUrlOffset = fbb.writeString(object.profileImageUrl);
          final profileThumbnailOffset =
              fbb.writeString(object.profileThumbnail);
          final statusOffset = fbb.writeString(object.status);
          fbb.startTable(7);
          fbb.addInt64(0, object.boxId);
          fbb.addOffset(1, idOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, profileImageUrlOffset);
          fbb.addOffset(4, profileThumbnailOffset);
          fbb.addOffset(5, statusOffset);
          fbb.finish(fbb.endTable());
          return object.boxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final boxIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final idParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final profileImageUrlParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final profileThumbnailParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final object = Profile(
              boxId: boxIdParam,
              id: idParam,
              name: nameParam,
              profileImageUrl: profileImageUrlParam,
              profileThumbnail: profileThumbnailParam,
              status: statusParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TbDocument] entity fields to define ObjectBox queries.
class TbDocument_ {
  /// See [TbDocument.internalId].
  static final internalId =
      obx.QueryIntegerProperty<TbDocument>(_entities[0].properties[0]);

  /// See [TbDocument.id].
  static final id =
      obx.QueryStringProperty<TbDocument>(_entities[0].properties[1]);

  /// See [TbDocument.content].
  static final content =
      obx.QueryStringProperty<TbDocument>(_entities[0].properties[2]);

  /// See [TbDocument.metadata].
  static final metadata =
      obx.QueryStringProperty<TbDocument>(_entities[0].properties[3]);

  /// See [TbDocument.embedding].
  static final embedding =
      obx.QueryHnswProperty<TbDocument>(_entities[0].properties[4]);
}

/// [Profile] entity fields to define ObjectBox queries.
class Profile_ {
  /// See [Profile.boxId].
  static final boxId =
      obx.QueryIntegerProperty<Profile>(_entities[1].properties[0]);

  /// See [Profile.id].
  static final id =
      obx.QueryStringProperty<Profile>(_entities[1].properties[1]);

  /// See [Profile.name].
  static final name =
      obx.QueryStringProperty<Profile>(_entities[1].properties[2]);

  /// See [Profile.profileImageUrl].
  static final profileImageUrl =
      obx.QueryStringProperty<Profile>(_entities[1].properties[3]);

  /// See [Profile.profileThumbnail].
  static final profileThumbnail =
      obx.QueryStringProperty<Profile>(_entities[1].properties[4]);

  /// See [Profile.status].
  static final status =
      obx.QueryStringProperty<Profile>(_entities[1].properties[5]);
}
